version: '3.5'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./dev-docker/Dockerfile
    ports:
      - $HTTP_EXPOSING_PORT:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./dev-docker/config/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./dev-docker/config/php/custom.ini:/etc/php7/conf.d/custom.ini
      - ./dev-docker/config/php/fpm/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./dev-docker/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./dev-docker/log/nginx/:/var/log/nginx/
      - ./dev-docker/log/wordpress/:/var/log/wordpress/
      - ./html/:/var/www/html/
      - ./.env:/var/www/.env
      - ./wp-config.php:/var/www/wp-config.php
    env_file:
      - ./.env
    environment:
      - DB_CONNECTION
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=host.docker.internal:3308
      - DB_USER
      - DB_NAME
      - WP_DEBUG
      - WP_DEBUG_LOG
      - SAVEQUERIES
      # Variables can be found here https://github.com/serversideup/docker-php/tree/main#environment-variables
      - PHP_TIMEZONE
      - PHP_MAX_EXECUTION_TIME
      - PHP_MEMORY_LIMIT
      - PHP_POST_MAX_SIZE
      - PHP_UPLOAD_MAX_FILESIZE
      - PHP_SENDMAIL_PATH="/usr/sbin/sendmail -t -i"

  # mysql8:
  #   image: mysql:8
  #   command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   ports:
  #     - 3306
  #   volumes:
  #     - mysql_db:/var/lib/mysql
  #     - './dev-docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
  #     - MYSQL_DATABASE=$DB_NAME
  #     - MYSQL_PASSWORD=$DB_PASSWORD
  #     - MYSQL_USER=$DB_USER
volumes:
  mysql_db:
