services:
  wordpress:
    build:
      context: .
      dockerfile: ./dev-docker/Dockerfile-nginx
    ports:
      - ${HTTP_EXPOSING_PORT}:80
      - ${HTTPS_EXPOSING_PORT}:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      # # For config nginx
      - ./dev-docker/config/nginx/http.conf:/etc/nginx/site-opts.d/http.conf
      - ./dev-docker/config/nginx/https.conf:/etc/nginx/site-opts.d/https.conf
      - ./dev-docker/config/php/custom.ini:/etc/php/8.0/cli/conf.d/99-custom.ini
      - ./dev-docker/config/php/xdebug.ini:/etc/php/8.0/cli/conf.d/20-xdebug.ini
      # For config apache
      # - ./dev-docker/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - ./dev-docker/config/apache/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
      # - ./dev-docker/config/apache/status.conf:/etc/apache2/mods-available/status.conf
      # - ./dev-docker/config/php/custom.ini:/etc/php/8.0/apache2/conf.d/zz-overrides.ini
      # - ./dev-docker/config/php/xdebug.ini:/etc/php/8.0/cli/conf.d/20-xdebug.ini
      ## For WordPress site
      - ./:/var/www/html/public
      - /var/www/html/public/wp-content/cache
      - /var/www/html/public/wp-content/upgrade
      - /var/www/html/public/wp-content/uploads
      # ## In case you want to use the sub-folder in your web root folder
      # - ./:/var/www/html/public/sub-folder
      # - /var/www/html/public/sub-folder/wp-content/cache
      # - /var/www/html/public/sub-folder/wp-content/upgrade
      # - /var/www/html/public/sub-folder/wp-content/uploads
      # Miscs
      - ./dev-docker/log/nginx/:/var/log/nginx/
      - ./dev-docker/log/wordpress/:/var/log/wordpress/
    env_file:
      - ./.env
    environment:
      - DB_CONNECTION
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_TABLE_PREFIX
      - DB_HOST
      - DB_USER
      - DB_NAME
      - WP_ENV
      - WP_BASE_PATH
      - WP_DEBUG
      - WP_DEBUG_LOG
      - WP_DEBUG_LOG_PATH
      - SAVEQUERIES
      - AUTH_KEY
      - SECURE_AUTH_KEY
      - LOGGED_IN_KEY
      - NONCE_KEY
      - AUTH_SALT
      - SECURE_AUTH_SALT
      - LOGGED_IN_SALT
      - NONCE_SALT
      - WP_CACHE_KEY_SALT
      - WP_ALLOW_MULTISITE
      - MULTISITE
      - SUBDOMAIN_INSTALL
      - DOMAIN_CURRENT_SITE
      - PATH_CURRENT_SITE
      - SITE_ID_CURRENT_SITE
      - BLOG_ID_CURRENT_SITE
      # WP App
      - ENPII_BASE_WP_APP_BASE_PATH
      - ENPII_BASE_WP_APP_PREFIX
      - ENPII_BASE_WP_API_PREFIX
      - WP_APP_TELESCOPE_ENABLED
      - WP_APP_TINKER_ENABLED
      - WP_APP_PASSPORT_ENABLED
      - ARTISAN_BINARY
      # PHP Env Variables
      - PHP_DATE_TIMEZONE
      - PHP_MAX_EXECUTION_TIME
      - PHP_MEMORY_LIMIT
      - PHP_POST_MAX_SIZE
      - PHP_UPLOAD_MAX_FILESIZE
      - PHP_DISPLAY_ERRORS
      - PHP_OPEN_BASEDIR
      - PHP_SENDMAIL_PATH
      - PHP_POOL_NAME

  mysql8:
    image: mysql:8
    command: mysqld --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${MYSQL_EXPOSING_PORT}:3306
    volumes:
      - mysql_db:/var/lib/mysql
      - './dev-docker/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
volumes:
  mysql_db:
